### PR TITLE
Fixing cases where site-id or site-name are changed

### LINKED ISSUE #787: diffing L2VPN has a problem trying to detect if the site ID has changed

### PR DESCRIPTION
**Pull request by jonstout**
If a node name is changed the site-name of any associated l2vpns must
be updated. This change updates the MX object's name on _update_cache
which allows us to compare the expected name against the active
name. If a difference is discovered we replace the site.

Fixes #787

### CODE REVIEW

File: perl-lib/OESS/lib/OESS/MPLS/Device/Juniper/MX.pm [hunk 1]
```diff
@@ -1217,26 +1217,34 @@ sub get_config_to_remove{
...
+                        next;
+                    }
+
+                    my $ints = $xp->find('./c:interface', $site);
+                    foreach my $int (@$ints){
+                        my $int_full_name = $xp->findvalue( './c:name', $int);
+                        my ($int_name,$unit_name) = split('\.',$name);
+                        $self->{'logger'}->debug("Checking to see if port: $name is part of circuit: $circuit_id");
+                        if(!$self->_is_circuit_on_port($circuit_id, $circuits, $int_name, $unit_name)){
                             $ri_dels .= "<instance><name>$name</name><protocols><l2vpn><site operation='delete'><name>$site_name</name></site></l2vpn></protocols></instance>";
```
Comment (ajragusa) [inline perl-lib/OESS/lib/OESS/MPLS/Device/Juniper/MX.pm]: Why are we deleting the entire site instead of just removing the interface from the list?

Comment (jonstout) [reply perl-lib/OESS/lib/OESS/MPLS/Device/Juniper/MX.pm]: There's no reason that I know of. I'll try addressing that.
